# Use the Python 3 alpine official image
FROM python:3-alpine

# Create and change to the app directory
WORKDIR /app

# Copy local code to the container image
COPY . .

# Install project dependencies (fix the filename)
RUN pip install --no-cache-dir -r requirements.txt

# Run the web service on container startup
CMD ["hypercorn", "main:app", "--bind", "0.0.0.0:$PORT"]
